version: "3.8"

services:
  server:
    image: ccr.ccs.tencentyun.com/5eqn/tint-server:main
    volumes:
      - data:/srv/db
    ports:
      - 54474:8000
    healthcheck:
      test: curl --fail 'http://localhost:8000' || exit 1
      interval: 1s
      timeout: 1s
      retries: 5

volumes:
  data:
